#!/bin/bash
#
# Script to run snapcraft
#
docker run --hostname "snapcraft" --env="USERNAME=$USER" --env="USERID=`id -u`" --env="GROUPID=`id -g`" --volume="`pwd`:/work" --volume="$HOME/.cache:/root/.cache" -ti lbthomsen/docker-snapcraft $@

# vim: ts=4 et nowrap autoindent
